<?xml version="1.0" encoding="UTF-8"?>

<pages xmlns="http://jboss.com/products/seam/pages" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://jboss.com/products/seam/pages http://jboss.com/products/seam/pages-2.1.xsd" no-conversation-view-id="/index.jspx" login-view-id="/login.jspx">  
  		
    <page view-id="/admin/*">
		<restrict>#{identity.loggedIn}</restrict>
	</page>

	<page view-id="/admin/tasks/viewTask.xhtml">
		<param name="taskId" value="#{jbpmProcessAction.taskId}" />
		<navigation>
			<rule if-outcome="next">
				<redirect view-id="/admin/tasks/tasks.xhtml" />
			</rule>
		</navigation>
	</page>


    
    <page view-id="/adminLogin.xhtml">     
        <navigation from-action="#{identity.login}">
           <redirect view-id="/admin/entities/summary.xhtml"/>
        </navigation>
	</page>
    		
  		
  	
  	<exception class="org.witchcraft.exceptions.BusinessException">
		<redirect>
			<message severity="warn">#{org.jboss.seam.handledException.message}
			</message>
		</redirect>
	</exception>
	<exception class="org.jboss.seam.framework.EntityNotFoundException">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Record not found</message>
		</redirect>
	</exception>
	<exception class="javax.persistence.EntityNotFoundException">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Record not found</message>
		</redirect>
	</exception>
	<exception class="javax.persistence.EntityExistsException">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Duplicate record</message>
		</redirect>
	</exception>
	<exception class="javax.persistence.OptimisticLockException">
		<end-conversation />
		<redirect view-id="/error.xhtml">
			<message severity="warn">Another user changed the same data, please
				try again
			</message>
		</redirect>
	</exception>
	<exception class="org.jboss.seam.security.AuthorizationException">
		<redirect>
			<message severity="error">You don't have permission to access this
				resource
			</message>
		</redirect>
	</exception>
	<exception class="org.jboss.seam.security.NotLoggedInException">
		<redirect view-id="/login.xhtml">
			<message severity="warn">#{messages['org.jboss.seam.NotLoggedIn']}
			</message>
		</redirect>
	</exception>
	<exception class="javax.faces.application.ViewExpiredException">
		<redirect view-id="/login.xhtml">
			<message severity="warn">Your session has timed out, please try
				again
			</message>
		</redirect>
	</exception>
	<exception class="org.jboss.seam.ConcurrentRequestTimeoutException"
		log-level="trace">
		<http-error error-code="503" />
	</exception>
	<exception>
		<redirect view-id="/error.xhtml">
			<message severity="error">Unexpected error, please try again
			</message>
		</redirect>
	</exception>


	<navigation from-action="#{identity.login}">
		<rule if="#{identity.loggedIn}">
			<redirect view-id="/admin/home.xhtml" />
		</rule>
	</navigation>


	<page view-id="/login.xhtml">
		<navigation from-action="#{identity.login}">
			<redirect view-id="/admin/home.xhtml" />
		</navigation>

		<navigation>
			<rule if="#{identity.loggedIn}">
				<redirect view-id="/admin/home.xhtml" />
			</rule>
		</navigation>
	</page>

  
</pages>
